### PR TITLE
Add optimized PQ for Gaussian distributions

### PR DESCRIPTION
**Pull request by danieldk**
Optimized PQ rotates the input space in order to balance variances over
subquantizers. This change adds the GaussianOPQ data structure, which
uses an optimization producedure for the rotation matrix that assumes
that the variables follow a Gaussian distribution (Ge et al., 2013).

It is a bit hard at this point to write proper unit tests for the higher-level
functions at this point. Eventually there should be some integration tests
that performs the reduction on a small embedding matrix, with some
expected minimum scores to detect regressions.

### CODE REVIEW

**Comment by twuebi** [comment]
Is the `--features=<BACKEND>` flag only necessary to run tests? 
It might be a good thing to state that somewhere, as the `undefined  reference to cblas_*` compiler errors first lead to me believe that the CBLAS library was missing.

**Comment by danieldk** [comment]
> Is the `--features=<BACKEND>` flag only necessary to run tests?

Not only for tests. LAPACK is needed for finding eigenvalues/vectors and also for SVD once OPQ is added. However, it is customary not to specify any default backends in library crates, so that binary crates can just specify the feature that they want (rather than first clearing features with `default-features`).

I also think picking a default backend is difficult. Many people prefer OpenBLAS because it is open source and does not favor one particular CPU vendor. But I prefer Intel MKL since it is *very* fast on Intel CPUs and is thread-safe, thus isn't incompatible with application threads.

I have added a project README with more information.

*errors first lead to me believe that the CBLAS library was missing.*

Note that there is no such thing as **the** C BLAS library. The closest thing is the netlib reference implementation, but since it is a reference implementation it is not optimized and slow (often an order of magnitude slower). Many Linux distributions default to ATLAS, which is not state-of-the-art anymore and lags behind. Sometimes OpenBLAS is provided, but e.g. Ubuntu LTSs have older versions that do not have kernels for your architecture and/or do not support dynamic arch selection yet (are thus compiled for the lowest common denominator). So in practice you have to select a BLAS version and compile or install it yourself. The nice thing about the OpenBLAS and Intel MKL crates is that they download and compile (in the case of OpenBLAS) the implementation, though depending on linkage and library load paths, it may still use the distribution's version.

**Comment by danieldk** [comment]
Thanks for the review and also for making me write the README 👍, it's very useful to have these things written down.

**Comment by sebpuetz** [comment]
I encountered an issue while trying to compile/test this the other day (posting here because I can't open an issue and remembered you discussing this here):

When using the OpenBLAS backend, Zen CPUs are not automatically recognized during compilation through the `openblas-src` crate. It's necessary to set a `OPENBLAS_TARGET=ZEN` variable. Took a bit to find the solution because I didn't realize the crate brought its own library and compiled it.

**Comment by danieldk** [comment]
Looking at OpenBLAS, there should be detection for ZEN. Did you check whether vanilla OpenBLAS 0.3.5 autodetection works?

**Comment by sebpuetz** [comment]
I was able to compile from sources and install through apt without issues.
Might be on the end of the Openblas-src crate. I found an issue in the GitHub OpenBLAS where Zen had not been added to the detection yet. Maybe the rust crate uses old OpenBLAS sources?

**Comment by sebpuetz** [comment]
I went through the dependencies of `ndarray_linalg`, they are on an older version of `openblas_src` that doesn't detect Ryzen 2 yet. Once they move up to `openblas_src = 0.7` in `ndarray_linalg`, it should be fine.

**Comment by danieldk** [comment]
Maybe send them a PR?

**Pull request merged**
